export const CARD_LIST_SUCCESS = 'CARD_LIST_SUCCESS';
export const CARD_LIST_LOADING = 'CARD_LIST_LOADING';
export const CARD_LIST_ERROR = 'CARD_LIST_ERROR';
export const CARD_LIST_RESET = 'CARD_LIST_RESET';
