export const BUDGET_LIST_LOADING = 'BUDGET_LIST_LOADING';
export const BUDGET_LIST_SUCCESS = 'BUDGET_LIST_SUCCESS';
export const BUDGET_LIST_ERROR = 'BUDGET_LIST_ERROR';
export const BUDGET_LIST_RESET = 'BUDGET_LIST_RESET';
