export const BUDGET_UPDATE_LOADING = 'BUDGET_UPDATE_LOADING';
export const BUDGET_UPDATE_SUCCESS = 'BUDGET_UPDATE_SUCCESS';
export const BUDGET_UPDATE_ERROR = 'BUDGET_UPDATE_ERROR';
export const BUDGET_UPDATE_RESET = 'BUDGET_UPDATE_RESET';
