export const HOUSE_VOUCHER_ADD_LOADING = 'HOUSE_VOUCHER_ADD_LOADING';
export const HOUSE_VOUCHER_ADD_SUCCESS = 'HOUSE_VOUCHER_ADD_SUCCESS';
export const HOUSE_VOUCHER_ADD_ERROR = 'HOUSE_VOUCHER_ADD_ERROR';
export const HOUSE_VOUCHER_ADD_RESET = 'HOUSE_VOUCHER_ADD_RESET';
