export const HOUSE_VOUCHER_LIST_LOADING = 'HOUSE_VOUCHER_LIST_LOADING';
export const HOUSE_VOUCHER_LIST_SUCCESS = 'HOUSE_VOUCHER_LIST_SUCCESS';
export const HOUSE_VOUCHER_LIST_ERROR = 'HOUSE_VOUCHER_LIST_ERROR';
export const HOUSE_VOUCHER_LIST_RESET = 'HOUSE_VOUCHER_LIST_RESET';
