export const BUDGET_ADD_LOADING = 'BUDGET_ADD_LOADING';
export const BUDGET_ADD_SUCCESS = 'BUDGET_ADD_SUCCESS';
export const BUDGET_ADD_ERROR = 'BUDGET_ADD_ERROR';
export const BUDGET_ADD_RESET = 'BUDGET_ADD_RESET';
