export const HOUSE_CURRENT_SUCCESS = 'HOUSE_CURRENT_SUCCESS';
export const HOUSE_CURRENT_LOADING = 'HOUSE_CURRENT_LOADING';
export const HOUSE_CURRENT_ERROR = 'HOUSE_CURRENT_ERROR';
export const HOUSE_CURRENT_RESET = 'HOUSE_CURRENT_RESET';
