export const HOUSE_MEMBER_LIST_SUCCESS = 'HOUSE_MEMBER_LIST_SUCCESS';
export const HOUSE_MEMBER_LIST_LOADING = 'HOUSE_MEMBER_LIST_LOADING';
export const HOUSE_MEMBER_LIST_ERROR = 'HOUSE_MEMBER_LIST_ERROR';
export const HOUSE_MEMBER_LIST_RESET = 'HOUSE_MEMBER_LIST_RESET';
