export const CARD_REMOVE_SUCCESS = 'CARD_REMOVE_SUCCESS';
export const CARD_REMOVE_LOADING = 'CARD_REMOVE_LOADING';
export const CARD_REMOVE_ERROR = 'CARD_REMOVE_ERROR';
export const CARD_REMOVE_RESET = 'CARD_REMOVE_RESET';
