export const SHOP_LIST_SUCCESS = 'SHOP_LIST_SUCCESS';
export const SHOP_LIST_LOADING = 'SHOP_LIST_LOADING';
export const SHOP_LIST_ERROR = 'SHOP_LIST_ERROR';
export const SHOP_LIST_RESET = 'SHOP_LIST_RESET';
