export const HOUSE_ADD_LOADING = 'HOUSE_ADD_LOADING';
export const HOUSE_ADD_SUCCESS = 'HOUSE_ADD_SUCCESS';
export const HOUSE_ADD_ERROR = 'HOUSE_ADD_ERROR';
export const HOUSE_ADD_RESET = 'HOUSE_ADD_RESET';
