export const HOUSE_LIST_SUCCESS = 'HOUSE_LIST_SUCCESS';
export const HOUSE_LIST_LOADING = 'HOUSE_LIST_LOADING';
export const HOUSE_LIST_ERROR = 'HOUSE_LIST_ERROR';
export const HOUSE_LIST_RESET = 'HOUSE_LIST_RESET';
