export const BUDGET_TRANSACTION_LIST_LOADING =
  'BUDGET_TRANSACTION_LIST_LOADING';
export const BUDGET_TRANSACTION_LIST_SUCCESS =
  'BUDGET_TRANSACTION_LIST_SUCCESS';
export const BUDGET_TRANSACTION_LIST_ERROR = 'BUDGET_TRANSACTION_LIST_ERROR';
export const BUDGET_TRANSACTION_LIST_RESET = 'BUDGET_TRANSACTION_LIST_RESET';
