export const USER_AUTHENTICATION_LOADING = 'USER_AUTHENTICATION_LOADING';
export const USER_AUTHENTICATION_ERROR = 'USER_AUTHENTICATION_ERROR';
export const USER_AUTHENTICATION_RESET = 'USER_AUTHENTICATION_RESET';
export const USER_AUTHENTICATION_LOGOUT = 'USER_AUTHENTICATION_LOGOUT';
export const USER_AUTHENTICATION_AUTHENTICATED =
  'USER_AUTHENTICATION_AUTHENTICATED';
