export const USER_REGISTRATION_LOADING = 'USER_REGISTRATION_LOADING';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_ERROR = 'USER_REGISTRATION_ERROR';
export const USER_REGISTRATION_RESET = 'USER_REGISTRATION_RESET';
