cluster.name: edgar
node.name: ${HOSTNAME}
#discovery.zen.ping.unicast.hosts: ["front01", "front02"]
discovery.zen.minimum_master_nodes: 1
# Needed for Docker
http.host: 0.0.0.0

plugin.mandatory: analysis-icu
node.data: true
node.master: true
bootstrap.memory_lock: true

# Disable X-Pack features
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
xpack.watcher.enabled: false
xpack.sql.enabled: false
xpack.graph.enabled: false
