export const RECIPE_CATEGORIES_LOADING = 'RECIPE_CATEGORIES_LOADING';
export const RECIPE_CATEGORIES_SUCCESS = 'RECIPE_CATEGORIES_SUCCESS';
export const RECIPE_CATEGORIES_RESET = 'RECIPE_CATEGORIES_RESET';
export const RECIPE_CATEGORIES_ERROR = 'RECIPE_CATEGORIES_ERROR';
