export const RECIPE_LIST_LOADING = 'RECIPE_LIST_LOADING';
export const RECIPE_LIST_SUCCESS = 'RECIPE_LIST_SUCCESS';
export const RECIPE_LIST_RESET = 'RECIPE_LIST_RESET';
export const RECIPE_LIST_ERROR = 'RECIPE_LIST_ERROR';
