export const RECIPE_ADD_LOADING = 'RECIPE_ADD_LOADING';
export const RECIPE_ADD_SUCCESS = 'RECIPE_ADD_SUCCESS';
export const RECIPE_ADD_RESET = 'RECIPE_ADD_RESET';
export const RECIPE_ADD_ERROR = 'RECIPE_ADD_ERROR';
