export const RECIPE_REMOVE_LOADING = 'RECIPE_REMOVE_LOADING';
export const RECIPE_REMOVE_SUCCESS = 'RECIPE_REMOVE_SUCCESS';
export const RECIPE_REMOVE_RESET = 'RECIPE_REMOVE_RESET';
export const RECIPE_REMOVE_ERROR = 'RECIPE_REMOVE_ERROR';
